Feature: Admin Changes Program Engagement Settings

@javascript
	Scenario: Checking the behavior of Program Engagement Settings according to the Ongoing/One-time engagement settings
    Given the current program is "primary":"albers"
    Given I have logged in as "ram@example.com"
    And I change engagement type of program "primary":"albers" to "career based and ongoing"
    And I follow "Manage"
    And I follow "Program Settings"
    And I follow "Mentoring Connection Settings"
    And I should not see "One-time Mentoring Settings"
    And I should not see "Consider Meeting as 'Elapsed'"
    And I should see "Ongoing Mentoring Settings"
    And I should see "Inactivity tracking"
    And I enable "calendar" feature that was removed from UI as super user of "primary":"albers"
    And I follow "Manage"
    And I follow "Program Settings"    
    And I follow "Mentoring Connection Settings"
    And I should see "One-time Mentoring Settings"
    And I should see "Consider Meeting as 'Elapsed'"
    And I should see "Ongoing Mentoring Settings"
    And I should see "Inactivity tracking"
    And I should see "Allow members of a mentoring connection to leave it without mentoring connection ending"
    And I should see "Recommended only for group mentoring connection"
    Then I should see "Allow members of a mentoring connection to change the expiration date of the mentoring connection"
    Then I should see "Allow members of a closed mentoring connection to reactivate the mentoring connection"
    And I change engagement type of program "primary":"albers" to "career based"
    And I follow "Manage"
    And I follow "Program Settings"
    And I follow "Mentoring Connection Settings"    
    And I should see "One-time Mentoring Settings"
    And I should see "Consider Meeting as 'Elapsed'"
    And I should not see "Ongoing Mentoring Settings"
    And I should not see "Inactivity tracking"
    And I logout

@javascript @cross_browser
  Scenario: Updating the Program Settings
    Given the current program is "primary":"albers"
    Given I have logged in as "ram@example.com"
    And I enable "calendar" feature that was removed from UI as super user of "primary":"albers"
    And I change engagement type of program "primary":"albers" to "career based and ongoing"
    And I follow "Manage"
    And I follow "Program Settings"    
    And I follow "Mentoring Connection Settings"
    And I should see "One-time Mentoring Settings"
    And I fill in "day(s) after the meeting request has been accepted and the meeting details were not decided" with "15"
    And I press "Save"
    And I should see "Your changes have been saved"
    And I choose "program_allow_one_to_many_mentoring_false"
    And I press "Save"
    And I should see "Your changes have been saved"
    And I choose "program_allow_one_to_many_mentoring_true"
    And I press "Save"
    And I should see "Your changes have been saved"
    And I choose "program_allow_users_to_leave_connection_true"
    And I press "Save"
    And I should see "Your changes have been saved"
    And I choose "program_allow_users_to_leave_connection_false"
    And I press "Save"
    And I should see "Your changes have been saved"
    And I choose "program_allow_to_change_connection_expiry_date_true"
    And I press "Save"
    And I should see "Your changes have been saved"
    And I choose "program_allow_to_change_connection_expiry_date_false"
    And I press "Save"
    And I should see "Your changes have been saved"
    And I select "2 months" from "program_inactivity_tracking_period_in_days"
    And I press "Save"
    And I should see "Your changes have been saved"
    And I should not see "program_feedback_survey_id"
    Then I enable "mentoring_connections_v2" feature as a super user
    And I follow "Manage"
    And I follow "Program Settings"    
    And I follow "Mentoring Connection Settings"
    And I select "Mentoring Connection Activity Feedback" from "program_feedback_survey_id"
    And I press "Save"
    And I should see "Your changes have been saved"
    And I check "program_auto_terminate_checkbox"
    And I press "Save"
    And I should see "Your changes have been saved"

@javascript
  Scenario: Updating the Engagement settings for a Project-based program
    Given the current program is "primary":"pbe"
    And pbe program has custom term
    And I have logged in as "ram@example.com"
    And I login as super user
    And I follow "Manage"
    And I follow "Program Settings"
    When I follow "Project Settings"
    Then I should not see "Project style"
    And I should not see "One-time Engagement Settings"
    And I should not see "Send Session Feedback Survey*"
    Then I should see "Allow members of a project to leave it without project ending"
    Then I should see "Recommended only for group project"
    Then I should see "Allow members of a project to change the expiration date of the project"
    Then I should see "Inactivity tracking"
    Then I should see "Check with user if inactive for more than"
    And I should not see "Allow Engagement Connection to be marked public"
    Then I should see "Advanced Options"
    Then I follow "Advanced Options"
    Then I should see "Reason for closing project"
    Then I should see "Enable hybrid templates"
    And I press "Save"
    Then I should see "Your changes have been saved"
    And I logout
