Feature: User signs in a new program

Background: Enable Enrollment Feature
  Given the feature "enrollment_page" is enabled for "primary"

@javascript @cross_browser
Scenario: User who is not part of program signs in. He should be redirected to new membership request page with appropriate messages
  Given the current program is "primary":"modprog"
  And I make "Upload your Resume" question available in the membership form for "student" in "primary":"modprog"
  And I make "Upload your Resume" question available in the membership form for "mentor" in "primary":"modprog"
  And I have logged in as "userram@example.com"
  And I should see the flash "To join as Mentor and Student, complete and submit the form below."
  And I select "Student" from "role_names_select"
  Then I upload the file "some_file.txt" for the file type question "Upload your Resume"
  Then I uncheck "some_file.txt"
  And I press "Submit"
  And I should see the flash "Your request has been sent to the program administrators. You will receive an email once the request is accepted."
  And I logout

  And I make "Upload your Resume" question available in the membership form for "mentor" in "primary":"modprog"
  Then I make the question "Upload your Resume" mandatory in "primary":"modprog"
  And I have logged in as "userram@example.com"
  And I should see the flash "Your request to join Moderated Program as Student is currently under review. Contact Administrator if you have any questions. To join as Mentor, complete and submit the form below."
  And I select "Mentor" from "role_names_select"
  And I press "Submit"
  And I should see the flash "Please fill the highlighted fields with appropriate values to proceed"
  Then I upload the file "some_file.txt" for the file type question "Upload your Resume"
  Then I uncheck "some_file.txt"
  Then I should see ".ajax-file-uploader" not hidden
  And I press "Submit"
  And I should see the flash "Please fill the highlighted fields with appropriate values to proceed"
  Then I check "some_file.txt"
  And I press "Submit"
  And I should see the flash "Your request has been sent to the program administrators. You will receive an email once the request is accepted."
  And I logout
  And I have logged in as "userram@example.com"
  And I should see the flash "Your request to join Moderated Program as Student and Mentor is currently under review. Contact Administrator if you have any questions."

@javascript @cross_browser
Scenario: Suspended User signs into a program. He should be redirected to new membership request page with appropriate messages
  Given the current program is "primary":"albers"
  Given the membership mode for "Mentor" is "Join Directly"
  Given the membership mode for "Student" is "Join Directly"
  Given the user with email "rahim@example.com" is suspended only in program "albers"
  And I have logged in as "rahim@example.com"
  And I should see the flash "Your profile in Albers Mentor Program is currently not active. To join as Mentor and Student, complete and submit the form below."
  And I select "Student" from "role_names_select"
  And I press "Submit"
  And I should see the flash "Your request has been sent to the program administrators. You will receive an email once the request is accepted."
  And I logout
  And I have logged in as "rahim@example.com"
  And I should see the flash "Your request to join Albers Mentor Program as Student is currently under review. Contact Administrator if you have any questions. To join as Mentor, complete and submit the form below."
  And I select "Mentor" from "role_names_select"
  And I press "Submit"
  And I should see the flash "Your request has been sent to the program administrators. You will receive an email once the request is accepted."
  And I logout
  And I have logged in as "rahim@example.com"
  And I should see the flash "Your request to join Albers Mentor Program as Student and Mentor is currently under review. Contact Administrator if you have any questions."
  And I logout
  And I have logged in as "ram@example.com"
  When I follow "Manage"
  Then I should see "Membership Requests"
  And I follow "Membership Requests"
  Then I should see state "Deactivated" for request from "rahim@example.com"

@javascript @cross_browser
Scenario: Admin edits pending membership request and updates the answers to the membership questions
  And I perform missed migrations
  Given I update the linkedin credentials for "primary"
  Given the current program is "primary":""
  And I have logged in as "ram@example.com"
  And I "enable" membership request customization for "primary"
  Given the current program is "primary":"albers"
  Then I make "Location" question admin only editable for "mentor" in "primary":"albers"
  And I make "Upload your Resume" question admin only visible for "mentor" in "primary":"albers"
  Then I make "Phone" question available in the membership form for "mentor" in "primary":"albers"
  Then I make "Work" question available in the membership form for "mentor" in "primary":"albers"
  Then I make the question "Work" mandatory in "primary":"albers"
  Then I make "About Me" question available in the membership form for "mentor" in "primary":"albers"
  Then I make "About Me" question text only in "primary"
  Then I make the question "About Me" mandatory in "primary":"albers"
  And I follow "Manage"
  And I follow "Membership Requests"
  Then I click on the individual dropdown for the membership request with email "student_5@example.com"
  And I follow "Edit Request"
  Then I should not see "Click here to import your experience"
  Then I fill in "membership_request_first_name" with ""
  Then I fill in "membership_request_last_name" with ""
  And I press "Update"
  And I should see the flash "Please fill the highlighted fields with appropriate values to proceed"
  And I set the allowed email domain to "chronus.com" in "primary"
  Then I fill in "membership_request_first_name" with "student 5"
  Then I fill in "membership_request_last_name" with "example"
  Then I fill in "membership_request_email" with "student_five@example.com"
  Then I fill in "profile_answers_8_" with "9123456789"
  And I press "Update"
  Then I should see "contains numeric characters"
  Then I should see "should be of chronus.com"
  Then I should see "Answer text cannot contain digits"
  Then I fill in "membership_request_first_name" with "student"
  Then I fill in "membership_request_last_name" with "five"
  Then I fill in "membership_request_email" with ""
  Then I fill in "profile_answers_8_" with "Just another guy"
  And I press "Update"
  #And I should see the flash "Please fill the highlighted fields with appropriate values to proceed"
  Then I fill in "membership_request_email" with "student_five@chronus.com"
  Then I upload the file "some_file.txt" for the file type question "Upload your Resume"
  Then I fill in "profile_answers_8_" with ""
  And I press "Update"
  And I should see the flash "The membership request has been updated successfully."
  Then I click on the individual dropdown for the membership request with email "student_five@chronus.com"
  And I follow "Edit Request"

  Given the current program is "primary":""
  And I follow "Manage"
  And I follow "Customize"
  And I open section with header "Basic Information"
  And I click on add new question
  And I fill in "profile_question_text_0" with "Upload your File"
  And I select "Upload File" from "profile_question_question_type_0"
  And I press "Save" within "form#edit_profile_question_"
  Then I wait for ajax to complete
  Then I follow "Programs"
  And I check "Student"
  Then I wait for ajax to complete
  And I check "Mentor"
  Then I wait for ajax to complete
  And I make "Upload your File" question available in the membership form for "mentor" in "primary":"albers"
  And I make the question "Upload your File" mandatory in "primary":"albers"

  Given the current program is "primary":"albers"
  And I follow "Manage"
  And I follow "Membership Requests"
  Then I click on the individual dropdown for the membership request with email "student_five@chronus.com"
  And I follow "Edit Request"
  And I fill in experience_question of "primary":"albers" with "Miami Corp, SVP"
  And I set the attachment field with ".ajax-file-uploader" to "handbook_test.txt"
  And I wait for upload to complete
  Then I should see "File was successfully scanned for viruses"
  And I press "Update"
  And I should see the flash "The membership request has been updated successfully."
  And I follow "Manage"
  And I follow "Membership Requests"
  Then I click on the individual dropdown for the membership request with email "student_five@chronus.com"
  And I follow "Edit Request"
  Then I uncheck "handbook_test.txt"
  And I press "Update"
  And I should see the flash "The membership request has been updated successfully."
  Then I visit the global profile of "student_five@chronus.com"
  Then I should see "student five"
  Then I should see "student_five@chronus.com"
  Then I should see "Miami Corp"
  Then I should see "some_file.txt"

@javascript @cross_browser
Scenario: User edits his pending membership request and updates the answers to the membership questions
  Given I perform missed migrations
  Given I update the linkedin credentials for "primary"
  And the current program is "primary":""

  Then I "enable" membership request customization for "primary"
  And I make "Location" question admin only editable for "mentor" in "primary":"modprog"
  And I make "Upload your Resume" question available in the membership form for "mentor" in "primary":"modprog"
  And I make "Phone" question available in the membership form for "mentor" in "primary":"modprog"
  And I make "Phone" question available in the membership form for "student" in "primary":"modprog"
  And I make "Work" question available in the membership form for "mentor" in "primary":"modprog"
  And I make "Work" question available in the membership form for "student" in "primary":"modprog"
  And I make the question "Work" mandatory in "primary":"modprog"
  And I make "About Me" question available in the membership form for "mentor" in "primary":"modprog"
  And I make the question "About Me" mandatory in "primary":"modprog"

  Given the current program is "primary":"modprog"
  When I have logged in as "userram@example.com"
  And I should see the flash "To join as Mentor and Student, complete and submit the form below."
  And I should see "Please complete the registration form provided below."
  And I should not see "Your Pending Requests"
  And I select "Mentor" from "role_names_select"
  And I should see "Phone"
  And I should see "About Me"
  And I should not see "Location"
  And I fill in "About Me" with "about me"
  And I fill in experience_question of "primary":"modprog" with "Miami Corp, SVP"
  When I press "Submit"
  Then I should see the flash "Your request has been sent to the program administrators."

  When I follow "Join"
  Then I should see "Your Pending Requests"
  And I should see "Kal Raman as Mentor"
  And I should see "Please complete the registration form provided below."
  When I follow "Update Details"
  Then I should see "Phone"
  And I should see "About Me"
  And I should not see "Location"
  Then I should see "Click here to import your experience"
  When I overwrite "existing" experience question of member "userram@example.com" with ", SVP"
  And I press "Update"
  Then I should see the flash "Please fill the highlighted fields with appropriate values to proceed"

  When I overwrite "existing" experience question of member "userram@example.com" with "Miami Corp, SVP"
  And I fill in "About Me" with ""
  And I press "Update"
  Then I should see the flash "Please fill the highlighted fields with appropriate values to proceed"

  And I fill in "About Me" with "about me"
  Then I press "Update"
  And I should see "Your Pending Requests"
  And I select "Student" from "role_names_select"
  And "existing" experience answer of member "userram@example.com" should contain "Miami Corp, SVP"
  And I should not see "About Me"
  When I press "Submit"
  Then I should see the flash "Your request has been sent to the program administrators."

  When I follow "Join"
  Then I should see "Your Pending Requests"
  And I should see "Kal Raman as Student"
  And I should not see "Please complete the registration form provided below."

@javascript @cross_browser
Scenario: User from other program requests for membership. Membership request answers are retained on role checkbox change.
  Given the current program is "primary":"albers"
  And I have logged in as "userram@example.com"
  And I click on profile picture and click "Edit Profile"
  And I click on the section with header "Basic Information"
  And I fill in "Location" with "Chennai, Tamil Nadu, India"
  And I press "submit_general"
  And I click on the section with header "Work and Education"
  And I fill in education_question of "primary":"albers" with "Ivy League,Masters,CS"
  And I fill in experience_question of "primary":"albers" with "Miami Corp, SVP"
  And I fill in publication_question of "primary":"albers" with "publication,publisher,author"
  And I fill in manager_question of "primary":"albers" with "first name,last name,manager@example.com"
  And I save the section "Work and Education"
  And I logout

  Then I make "Phone" question available in the membership form for "student" in "primary":"modprog"
  And I make "Phone" question available in the membership form for "mentor" in "primary":"modprog"
  And I make "Location" question available in the membership form for "student" in "primary":"modprog"
  And I make "Skype ID" question available in the membership form for "mentor" in "primary":"modprog"
  And I make special type and file type questions available in the membership form for "mentor" in "modprog" program
  And I make special type and file type questions available in the membership form for "student" in "modprog" program

  Given the current program is "primary":"modprog"
  And I have logged in as "userram@example.com"
  And I should see the flash "To join as Mentor and Student, complete and submit the form below."
  And I select "Student" from "role_names_select"

  Then I should see "Phone"
  And I should see "Location"
  And I should not see "Skype ID"
  And the "Location" field should contain "Chennai, Tamil Nadu, India" for member with email "userram@example.com"
  And "existing" education answer of member "userram@example.com" should contain "Ivy League,Masters,CS"
  And "existing" experience answer of member "userram@example.com" should contain "Miami Corp, SVP"
  And "existing" publication answer of member "userram@example.com" should contain "publication,publisher,author"
  And "existing" manager answer of member "userram@example.com" should contain "first name,last name,manager@example.com"

  Then I overwrite "existing" education question of member "userram@example.com" with ",BTech,IT"
  And I overwrite "existing" experience question of member "userram@example.com" with ",JobTitle"
  And I overwrite "existing" publication question of member "userram@example.com" with ",publisherNew,AuthorNew"
  And I overwrite "existing" manager question of member "userram@example.com" with ",,"
  And I follow "Add another degree"
  And I fill in education_question of "primary":"albers" with "Edu,BE,CS"
  And I follow "Add another position"
  And I fill in experience_question of "primary":"albers" with "Exp,Job"
  And I fill in "Phone" with "987654321"
  And I upload the file "some_file.txt" for the file type question "Upload your Resume"

  When I select "Mentor" from "role_names_select"
  Then I should see "Phone"
  And I should not see "Location"
  And I should see "Skype ID"
  And the "some_file.txt" checkbox should be checked
  And the "Phone" field should contain "987654321" for member with email "userram@example.com"
  And "existing" education answer of member "userram@example.com" should contain ",BTech,IT"
  And "existing" experience answer of member "userram@example.com" should contain ",JobTitle"
  And "existing" publication answer of member "userram@example.com" should contain ",publisherNew,AuthorNew"
  And "existing" manager answer of member "userram@example.com" should contain ",,"
  And "new" education answer of member "userram@example.com" should contain "Edu,BE,CS"
  And "new" experience answer of member "userram@example.com" should contain "Exp,Job"

  Then I overwrite "new" education question of member "userram@example.com" with "MIT,BE,CSE"
  And I overwrite "new" experience question of member "userram@example.com" with "MS,JobTitle"
  And I fill in "Skype ID" with "skypeID"

  When I select "Student" from "role_names_select"
  Then I should see "Phone"
  And I should see "Location"
  And I should not see "Skype ID"
  And the "Location" field should contain "Chennai, Tamil Nadu, India" for member with email "userram@example.com"

  When I select "Mentor" from "role_names_select"
  Then the "Skype ID" field should contain "" for member with email "userram@example.com"
  And I fill in "Skype ID" with "skypeID"
  When I press "Submit"
  Then I should see the flash "Please fill the highlighted fields with appropriate values to proceed"

  Then I overwrite "existing" education question of member "userram@example.com" with "CEG,BTech,IT"
  And I overwrite "existing" experience question of member "userram@example.com" with "Chronus,JobTitle"
  And I overwrite "existing" publication question of member "userram@example.com" with "PublTitle,publisherNew,AuthorNew"
  And I overwrite "existing" manager question of member "userram@example.com" with "Maanik,Baasha,maanikkam@example.com"
  When I press "Submit"
  Then I should see the flash "Your request has been sent to the program administrators. You will receive an email once the request is accepted."
  And I logout

  When I have logged in as "ram@example.com"
  And I follow "Manage"
  And I follow "Membership Requests"
  Then I should see "Kal Raman"
  When I follow "Show more"
  Then I should see "987654321"
  And I should see "skypeID"
  And I should see "CEG, BTech in IT"
  And I should see "MIT, BE in CSE"
  And I should see "Chronus, JobTitle"
  And I should see "MS, JobTitle"
  And I should see "PublTitle"
  And I should see "publisherNew"
  And I should see "Authors:AuthorNew"
  And I should see "Maanik Baasha (maanikkam@example.com)"
  And I should see "some_file.txt"
